algoritmo "Lista1 exe 2"
// Função :
// Autor :Joziel Dias Rocha
// Data : 15/02/2019
// Seção de Declarações 
var
kf, ki, litros: Inteiro
Media: Real


inicio
Escreva("Informe o k/m Final:")
Leia(kf)
Escreva("Informe o k/m inicial:")
Leia(ki)
Escreva("Litros gastos na viagem:")
Leia(litros)
Media <- (kf - ki)/litros
Escreva("Media da gasto na viagem:", Media, " KM Litros")

// Seção de Comandos 
fimalgoritmo
