algoritmo "LISTA1_EX01"
// Função :
// Autor : JOZIEL DIAS ROCHA
// Data : 14/02/2019
// Seção de Declarações 
var
V1,V2,V3: INTEIRO
MEDIA: REAL

inicio
ESCREVA("INFORME O PRIMEIRO VALOR:")
LEIA(V1)
ESCREVA("INFORME O SEGUNDO  VALOR:")
LEIA(V2)
ESCREVA("INFORME O TERCEIRO VALOR:")
LEIA(V3)
MEDIA <- ((V1*3)+(V2*4)+(V3*6))/13
ESCREVA("MEDIA =", MEDIA)

// Seção de Comandos 
fimalgoritmo
